# Generated by Django 4.0.4 on 2022-04-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('point_depart', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('altitude_depart', models.CharField(max_length=400)),
                ('altitude_minimale', models.CharField(max_length=200)),
                ('altitude_maximale', models.CharField(max_length=200)),
                ('denivele_positif_cumule', models.CharField(max_length=200)),
                ('denivele_negatif_cumule', models.CharField(max_length=200)),
                ('duree', models.CharField(max_length=200)),
                ('difficulte', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
            ],
        ),
    ]
