# Generated by Django 4.0.4 on 2022-04-19 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itineraires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraire',
            name='altitude_depart',
            field=models.FloatField(verbose_name='Altitude de départ (m)'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='altitude_maximale',
            field=models.FloatField(verbose_name='Altitude maximale (m)'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='altitude_minimale',
            field=models.FloatField(verbose_name='Altitude minimale (m)'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='denivele_negatif_cumule',
            field=models.FloatField(verbose_name='Dénivelé négatif cumulé (m)'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='denivele_positif_cumule',
            field=models.FloatField(verbose_name='Dénivelé positif cumulé (m)'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='difficulte',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Difficulté (de 1 à 5)'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='duree',
            field=models.FloatField(verbose_name='Durée (en heure)'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='point_depart',
            field=models.CharField(max_length=200, verbose_name='Point de départ'),
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sortie', models.FloatField(verbose_name='Date de la sortie')),
                ('duree_reelle', models.FloatField(verbose_name='Durée réelle (en heure)')),
                ('nombre_personne', models.FloatField(verbose_name='Nombre de personnes ayant réalisé la sortie')),
                ('experience', models.IntegerField(choices=[(1, 'Tous débutant'), (2, 'Tous expérimenté'), (3, 'Mixte')], default=1, verbose_name='Expérience du groupe')),
                ('meteo', models.IntegerField(choices=[(1, 'Bonne'), (2, 'Moyenne'), (3, 'Mauvaise')], default=1, verbose_name='Météo')),
                ('difficulte_ressentie', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Difficulté (de 1 à 5)')),
                ('itineraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraires.itineraire')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
